# Generated by Django 4.1 on 2023-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
