# Generated by Django 4.1 on 2023-05-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("blog", "0002_alter_author_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.author",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
